### ISSUE TITLE
Example 8 SPO2 Code Error

### ISSUE THREAD

**Issue by bhernandez0** [sparkfun/MAX30105_Particle_Sensor_Breakout#4]
When I try to upload the code to a Arduino Pro Mini I am receiving this error:

Example8_SPO2:96: error: cannot convert 'uint16_t* {aka unsigned int*}' to 'uint32_t* {aka long unsigned int*}' for argument '1' to 'void maxim_heart_rate_and_oxygen_saturation(uint32_t*, int32_t, uint32_t*, int32_t*, int8_t*, int32_t*, int8_t*)'

   maxim_heart_rate_and_oxygen_saturation(irBuffer, bufferLength, redBuffer, &spo2, &validSPO2, &heartRate, &validHeartRate);

Is there a fix for this?

**Comment by nseidle** [comment]
Ya, it's this [line](https://github.com/sparkfun/SparkFun_MAX3010x_Sensor_Library/blob/master/src/spo2_algorithm.cpp#L63) (ok a couple of these lines in h and ino). Needs to be changed to

    #if defined(__AVR_ATmega328P__) || defined(__AVR_ATmega168__)

**Comment by nseidle** [comment]
Should be fixed in v1.0.3

**Comment by bhernandez0** [comment]
Thank You!!! Works great now

**Comment by nseidle** [comment]
Excellent!

**Comment by zlocimir** [comment]
Any idea on how to get it working on NodeMCU?
Every other example is working just fine

This is what serial monitor returns:
 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
